version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: spark_user
      POSTGRES_PASSWORD: spark_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./исходные данные:/import_data
    networks:
      - bigdata

  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark:/opt/spark-apps
      - ./jars:/opt/spark/jars
    depends_on:
      - postgres
    networks:
      - bigdata

  spark-worker:
    image: bitnami/spark:3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=yes
    depends_on:
      - spark-master
    volumes:
      - ./spark:/opt/spark-apps
      - ./jars:/opt/spark/jars
    networks:
      - bigdata

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - bigdata

volumes:
  pgdata:

networks:
  bigdata:
    driver: bridge

  